use_frameworks!

platform :ios, '8.0'

target 'PngGif_Example' do
  pod 'PngGif', :path => '../'

  target 'PngGif_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
